// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200321205341_reseeddb")]
    partial class reseeddb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaseCount")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            DeliveryId = 1,
                            CaseCount = 100,
                            DeliveryTime = "08:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 2,
                            CaseCount = 65,
                            DeliveryTime = "09:30:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 3,
                            CaseCount = 98,
                            DeliveryTime = "10:11:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 4,
                            CaseCount = 72,
                            DeliveryTime = "6:30:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 5,
                            CaseCount = 89,
                            DeliveryTime = "12:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 6,
                            CaseCount = 34,
                            DeliveryTime = "12:45:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 7,
                            CaseCount = 78,
                            DeliveryTime = "05:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 8,
                            CaseCount = 65,
                            DeliveryTime = "12:45:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 9,
                            CaseCount = 89,
                            DeliveryTime = "10:30:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 10,
                            CaseCount = 34,
                            DeliveryTime = "9:45:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 11,
                            CaseCount = 45,
                            DeliveryTime = "11:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 12,
                            CaseCount = 87,
                            DeliveryTime = "9:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 13,
                            CaseCount = 58,
                            DeliveryTime = "8:00:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 14,
                            CaseCount = 37,
                            DeliveryTime = "7:45:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 15,
                            CaseCount = 20,
                            DeliveryTime = "10:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 16,
                            CaseCount = 60,
                            DeliveryTime = "13:45:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 17,
                            CaseCount = 90,
                            DeliveryTime = "14:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 18,
                            CaseCount = 50,
                            DeliveryTime = "12:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 19,
                            CaseCount = 70,
                            DeliveryTime = "15:00:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 20,
                            CaseCount = 65,
                            DeliveryTime = "13:45:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 21,
                            CaseCount = 72,
                            DeliveryTime = "13:00:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 22,
                            CaseCount = 75,
                            DeliveryTime = "06:30:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 23,
                            CaseCount = 125,
                            DeliveryTime = "06:00:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 24,
                            CaseCount = 100,
                            DeliveryTime = "12:15:00",
                            DriverId = 3
                        },
                        new
                        {
                            DeliveryId = 25,
                            CaseCount = 295,
                            DeliveryTime = "12:00:00",
                            DriverId = 3
                        });
                });

            modelBuilder.Entity("Repository.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RouteId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Name = "Aaron Madison",
                            PhoneNumber = "123-456-7891",
                            Position = "Sales Representative",
                            RouteId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            Name = "Amanda Miller",
                            PhoneNumber = "123-456-7891",
                            Position = "Merchandiser",
                            RouteId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            Name = "David Wroblewski",
                            PhoneNumber = "123-456-7891",
                            Position = "Driver",
                            RouteId = 3
                        });
                });

            modelBuilder.Entity("Repository.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RouteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            RouteName = "CWMLAA",
                            ScheduleId = 11
                        },
                        new
                        {
                            RouteId = 2,
                            RouteName = "CWMLAB",
                            ScheduleId = 12
                        },
                        new
                        {
                            RouteId = 3,
                            RouteName = "CWMLAC",
                            ScheduleId = 13
                        });
                });

            modelBuilder.Entity("Repository.Models.RouteStore", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("RouteStoreId")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("RouteStores");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            StoreId = 1,
                            RouteStoreId = 1
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 2,
                            RouteStoreId = 2
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 3,
                            RouteStoreId = 3
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 4,
                            RouteStoreId = 4
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 5,
                            RouteStoreId = 5
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 6,
                            RouteStoreId = 6
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 7,
                            RouteStoreId = 7
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 8,
                            RouteStoreId = 8
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 9,
                            RouteStoreId = 9
                        },
                        new
                        {
                            RouteId = 1,
                            StoreId = 10,
                            RouteStoreId = 10
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 1,
                            RouteStoreId = 11
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 2,
                            RouteStoreId = 12
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 3,
                            RouteStoreId = 13
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 4,
                            RouteStoreId = 14
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 5,
                            RouteStoreId = 15
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 6,
                            RouteStoreId = 16
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 7,
                            RouteStoreId = 17
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 8,
                            RouteStoreId = 18
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 9,
                            RouteStoreId = 19
                        },
                        new
                        {
                            RouteId = 2,
                            StoreId = 10,
                            RouteStoreId = 20
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 1,
                            RouteStoreId = 21
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 2,
                            RouteStoreId = 22
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 3,
                            RouteStoreId = 23
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 4,
                            RouteStoreId = 24
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 5,
                            RouteStoreId = 25
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 6,
                            RouteStoreId = 26
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 7,
                            RouteStoreId = 27
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 8,
                            RouteStoreId = 28
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 9,
                            RouteStoreId = 29
                        },
                        new
                        {
                            RouteId = 3,
                            StoreId = 10,
                            RouteStoreId = 30
                        });
                });

            modelBuilder.Entity("Repository.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            StoreId = 1
                        },
                        new
                        {
                            ScheduleId = 2,
                            StoreId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            StoreId = 3
                        },
                        new
                        {
                            ScheduleId = 4,
                            StoreId = 4
                        },
                        new
                        {
                            ScheduleId = 5,
                            StoreId = 5
                        },
                        new
                        {
                            ScheduleId = 6,
                            StoreId = 6
                        },
                        new
                        {
                            ScheduleId = 7,
                            StoreId = 7
                        },
                        new
                        {
                            ScheduleId = 8,
                            StoreId = 8
                        },
                        new
                        {
                            ScheduleId = 9,
                            StoreId = 9
                        },
                        new
                        {
                            ScheduleId = 10,
                            StoreId = 10
                        },
                        new
                        {
                            ScheduleId = 11,
                            EmployeeId = 1
                        },
                        new
                        {
                            ScheduleId = 12,
                            EmployeeId = 2
                        },
                        new
                        {
                            ScheduleId = 13,
                            EmployeeId = 3
                        });
                });

            modelBuilder.Entity("Repository.Models.ScheduleStop", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleStopId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId", "StopId");

                    b.HasIndex("StopId");

                    b.ToTable("ScheduleStops");

                    b.HasData(
                        new
                        {
                            ScheduleId = 11,
                            StopId = 1,
                            ScheduleStopId = 1
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 2,
                            ScheduleStopId = 2
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 3,
                            ScheduleStopId = 3
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 4,
                            ScheduleStopId = 4
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 5,
                            ScheduleStopId = 5
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 16,
                            ScheduleStopId = 16
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 17,
                            ScheduleStopId = 17
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 18,
                            ScheduleStopId = 18
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 19,
                            ScheduleStopId = 19
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 20,
                            ScheduleStopId = 20
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 31,
                            ScheduleStopId = 31
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 32,
                            ScheduleStopId = 32
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 33,
                            ScheduleStopId = 33
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 34,
                            ScheduleStopId = 34
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 35,
                            ScheduleStopId = 35
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 46,
                            ScheduleStopId = 46
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 47,
                            ScheduleStopId = 47
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 48,
                            ScheduleStopId = 48
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 49,
                            ScheduleStopId = 49
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 50,
                            ScheduleStopId = 50
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 61,
                            ScheduleStopId = 61
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 62,
                            ScheduleStopId = 62
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 63,
                            ScheduleStopId = 63
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 64,
                            ScheduleStopId = 64
                        },
                        new
                        {
                            ScheduleId = 11,
                            StopId = 65,
                            ScheduleStopId = 65
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 6,
                            ScheduleStopId = 6
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 7,
                            ScheduleStopId = 7
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 8,
                            ScheduleStopId = 8
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 9,
                            ScheduleStopId = 9
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 10,
                            ScheduleStopId = 10
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 21,
                            ScheduleStopId = 21
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 22,
                            ScheduleStopId = 22
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 23,
                            ScheduleStopId = 23
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 24,
                            ScheduleStopId = 24
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 25,
                            ScheduleStopId = 25
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 36,
                            ScheduleStopId = 36
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 37,
                            ScheduleStopId = 37
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 38,
                            ScheduleStopId = 38
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 39,
                            ScheduleStopId = 39
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 40,
                            ScheduleStopId = 40
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 51,
                            ScheduleStopId = 51
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 52,
                            ScheduleStopId = 52
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 53,
                            ScheduleStopId = 53
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 54,
                            ScheduleStopId = 54
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 55,
                            ScheduleStopId = 55
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 66,
                            ScheduleStopId = 66
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 67,
                            ScheduleStopId = 67
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 68,
                            ScheduleStopId = 68
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 69,
                            ScheduleStopId = 69
                        },
                        new
                        {
                            ScheduleId = 12,
                            StopId = 70,
                            ScheduleStopId = 70
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 11,
                            ScheduleStopId = 11
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 12,
                            ScheduleStopId = 12
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 13,
                            ScheduleStopId = 13
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 14,
                            ScheduleStopId = 14
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 15,
                            ScheduleStopId = 15
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 26,
                            ScheduleStopId = 26
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 27,
                            ScheduleStopId = 27
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 28,
                            ScheduleStopId = 28
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 29,
                            ScheduleStopId = 29
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 30,
                            ScheduleStopId = 30
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 41,
                            ScheduleStopId = 41
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 42,
                            ScheduleStopId = 42
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 43,
                            ScheduleStopId = 43
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 44,
                            ScheduleStopId = 44
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 45,
                            ScheduleStopId = 45
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 56,
                            ScheduleStopId = 56
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 57,
                            ScheduleStopId = 57
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 58,
                            ScheduleStopId = 58
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 59,
                            ScheduleStopId = 59
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 60,
                            ScheduleStopId = 60
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 71,
                            ScheduleStopId = 71
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 72,
                            ScheduleStopId = 72
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 73,
                            ScheduleStopId = 73
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 74,
                            ScheduleStopId = 74
                        },
                        new
                        {
                            ScheduleId = 13,
                            StopId = 75,
                            ScheduleStopId = 75
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 1,
                            ScheduleStopId = 76
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 11,
                            ScheduleStopId = 77
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 23,
                            ScheduleStopId = 78
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 31,
                            ScheduleStopId = 78
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 41,
                            ScheduleStopId = 79
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 53,
                            ScheduleStopId = 80
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 61,
                            ScheduleStopId = 81
                        },
                        new
                        {
                            ScheduleId = 1,
                            StopId = 71,
                            ScheduleStopId = 82
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 2,
                            ScheduleStopId = 83
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 12,
                            ScheduleStopId = 84
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 24,
                            ScheduleStopId = 85
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 32,
                            ScheduleStopId = 86
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 42,
                            ScheduleStopId = 87
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 54,
                            ScheduleStopId = 88
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 62,
                            ScheduleStopId = 89
                        },
                        new
                        {
                            ScheduleId = 2,
                            StopId = 72,
                            ScheduleStopId = 90
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 3,
                            ScheduleStopId = 91
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 13,
                            ScheduleStopId = 92
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 25,
                            ScheduleStopId = 93
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 33,
                            ScheduleStopId = 94
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 43,
                            ScheduleStopId = 95
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 55,
                            ScheduleStopId = 96
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 63,
                            ScheduleStopId = 97
                        },
                        new
                        {
                            ScheduleId = 3,
                            StopId = 73,
                            ScheduleStopId = 98
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 4,
                            ScheduleStopId = 99
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 21,
                            ScheduleStopId = 100
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 29,
                            ScheduleStopId = 101
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 34,
                            ScheduleStopId = 102
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 51,
                            ScheduleStopId = 103
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 59,
                            ScheduleStopId = 104
                        },
                        new
                        {
                            ScheduleId = 4,
                            StopId = 64,
                            ScheduleStopId = 105
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 5,
                            ScheduleStopId = 106
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 22,
                            ScheduleStopId = 107
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 30,
                            ScheduleStopId = 108
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 35,
                            ScheduleStopId = 109
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 52,
                            ScheduleStopId = 110
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 60,
                            ScheduleStopId = 111
                        },
                        new
                        {
                            ScheduleId = 5,
                            StopId = 65,
                            ScheduleStopId = 112
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 6,
                            ScheduleStopId = 113
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 14,
                            ScheduleStopId = 114
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 26,
                            ScheduleStopId = 115
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 34,
                            ScheduleStopId = 116
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 44,
                            ScheduleStopId = 117
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 56,
                            ScheduleStopId = 118
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 64,
                            ScheduleStopId = 119
                        },
                        new
                        {
                            ScheduleId = 6,
                            StopId = 74,
                            ScheduleStopId = 120
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 7,
                            ScheduleStopId = 121
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 15,
                            ScheduleStopId = 122
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 20,
                            ScheduleStopId = 123
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 37,
                            ScheduleStopId = 124
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 45,
                            ScheduleStopId = 125
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 50,
                            ScheduleStopId = 126
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 67,
                            ScheduleStopId = 127
                        },
                        new
                        {
                            ScheduleId = 7,
                            StopId = 75,
                            ScheduleStopId = 128
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 8,
                            ScheduleStopId = 129
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 16,
                            ScheduleStopId = 130
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 26,
                            ScheduleStopId = 131
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 38,
                            ScheduleStopId = 132
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 46,
                            ScheduleStopId = 133
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 56,
                            ScheduleStopId = 134
                        },
                        new
                        {
                            ScheduleId = 8,
                            StopId = 68,
                            ScheduleStopId = 135
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 9,
                            ScheduleStopId = 136
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 17,
                            ScheduleStopId = 137
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 27,
                            ScheduleStopId = 138
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 39,
                            ScheduleStopId = 139
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 47,
                            ScheduleStopId = 140
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 57,
                            ScheduleStopId = 141
                        },
                        new
                        {
                            ScheduleId = 9,
                            StopId = 69,
                            ScheduleStopId = 142
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 10,
                            ScheduleStopId = 143
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 18,
                            ScheduleStopId = 144
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 28,
                            ScheduleStopId = 145
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 40,
                            ScheduleStopId = 146
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 48,
                            ScheduleStopId = 147
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 58,
                            ScheduleStopId = 148
                        },
                        new
                        {
                            ScheduleId = 10,
                            StopId = 70,
                            ScheduleStopId = 149
                        });
                });

            modelBuilder.Entity("Repository.Models.Stop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StopId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Stops");

                    b.HasData(
                        new
                        {
                            StopId = 1,
                            DayOfWeek = 1,
                            DeliveryId = 1,
                            EmployeeId = 1,
                            StoreId = 1,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 2,
                            DayOfWeek = 1,
                            DeliveryId = 2,
                            EmployeeId = 1,
                            StoreId = 2,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 3,
                            DayOfWeek = 1,
                            DeliveryId = 3,
                            EmployeeId = 1,
                            StoreId = 3,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 4,
                            DayOfWeek = 1,
                            EmployeeId = 1,
                            StoreId = 4,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 5,
                            DayOfWeek = 1,
                            EmployeeId = 1,
                            StoreId = 5,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 6,
                            DayOfWeek = 1,
                            DeliveryId = 4,
                            EmployeeId = 2,
                            StoreId = 6,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 7,
                            DayOfWeek = 1,
                            DeliveryId = 5,
                            EmployeeId = 2,
                            StoreId = 7,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 8,
                            DayOfWeek = 1,
                            EmployeeId = 2,
                            StoreId = 8,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 9,
                            DayOfWeek = 1,
                            EmployeeId = 2,
                            StoreId = 9,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 10,
                            DayOfWeek = 1,
                            EmployeeId = 2,
                            StoreId = 10,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 11,
                            DayOfWeek = 1,
                            DeliveryId = 1,
                            EmployeeId = 3,
                            StoreId = 1,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 12,
                            DayOfWeek = 1,
                            DeliveryId = 2,
                            EmployeeId = 3,
                            StoreId = 2,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 13,
                            DayOfWeek = 1,
                            DeliveryId = 3,
                            EmployeeId = 3,
                            StoreId = 3,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 14,
                            DayOfWeek = 1,
                            DeliveryId = 4,
                            EmployeeId = 3,
                            StoreId = 6,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 15,
                            DayOfWeek = 1,
                            DeliveryId = 5,
                            EmployeeId = 3,
                            StoreId = 7,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 16,
                            DayOfWeek = 2,
                            DeliveryId = 6,
                            EmployeeId = 1,
                            StoreId = 8,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 17,
                            DayOfWeek = 2,
                            DeliveryId = 7,
                            EmployeeId = 1,
                            StoreId = 9,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 18,
                            DayOfWeek = 2,
                            DeliveryId = 8,
                            EmployeeId = 1,
                            StoreId = 10,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 19,
                            DayOfWeek = 2,
                            EmployeeId = 1,
                            StoreId = 6,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 20,
                            DayOfWeek = 2,
                            EmployeeId = 1,
                            StoreId = 7,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 21,
                            DayOfWeek = 2,
                            DeliveryId = 9,
                            EmployeeId = 2,
                            StoreId = 4,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 22,
                            DayOfWeek = 2,
                            DeliveryId = 10,
                            EmployeeId = 2,
                            StoreId = 5,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 23,
                            DayOfWeek = 2,
                            EmployeeId = 2,
                            StoreId = 1,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 24,
                            DayOfWeek = 2,
                            EmployeeId = 2,
                            StoreId = 2,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 25,
                            DayOfWeek = 2,
                            EmployeeId = 2,
                            StoreId = 3,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 26,
                            DayOfWeek = 2,
                            DeliveryId = 6,
                            EmployeeId = 3,
                            StoreId = 8,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 27,
                            DayOfWeek = 2,
                            DeliveryId = 7,
                            EmployeeId = 3,
                            StoreId = 9,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 28,
                            DayOfWeek = 2,
                            DeliveryId = 8,
                            EmployeeId = 3,
                            StoreId = 10,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 29,
                            DayOfWeek = 2,
                            DeliveryId = 9,
                            EmployeeId = 3,
                            StoreId = 4,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 30,
                            DayOfWeek = 2,
                            DeliveryId = 10,
                            EmployeeId = 3,
                            StoreId = 5,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 31,
                            DayOfWeek = 3,
                            DeliveryId = 11,
                            EmployeeId = 1,
                            StoreId = 1,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 32,
                            DayOfWeek = 3,
                            DeliveryId = 12,
                            EmployeeId = 1,
                            StoreId = 2,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 33,
                            DayOfWeek = 3,
                            DeliveryId = 13,
                            EmployeeId = 1,
                            StoreId = 3,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 34,
                            DayOfWeek = 3,
                            EmployeeId = 1,
                            StoreId = 4,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 35,
                            DayOfWeek = 3,
                            EmployeeId = 1,
                            StoreId = 5,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 36,
                            DayOfWeek = 3,
                            DeliveryId = 14,
                            EmployeeId = 2,
                            StoreId = 6,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 37,
                            DayOfWeek = 3,
                            DeliveryId = 15,
                            EmployeeId = 2,
                            StoreId = 7,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 38,
                            DayOfWeek = 3,
                            EmployeeId = 2,
                            StoreId = 8,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 39,
                            DayOfWeek = 3,
                            EmployeeId = 2,
                            StoreId = 9,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 40,
                            DayOfWeek = 3,
                            EmployeeId = 2,
                            StoreId = 10,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 41,
                            DayOfWeek = 3,
                            DeliveryId = 11,
                            EmployeeId = 3,
                            StoreId = 1,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 42,
                            DayOfWeek = 3,
                            DeliveryId = 12,
                            EmployeeId = 3,
                            StoreId = 2,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 43,
                            DayOfWeek = 3,
                            DeliveryId = 13,
                            EmployeeId = 3,
                            StoreId = 3,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 44,
                            DayOfWeek = 3,
                            DeliveryId = 14,
                            EmployeeId = 3,
                            StoreId = 6,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 45,
                            DayOfWeek = 3,
                            DeliveryId = 15,
                            EmployeeId = 3,
                            StoreId = 7,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 46,
                            DayOfWeek = 4,
                            DeliveryId = 16,
                            EmployeeId = 1,
                            StoreId = 8,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 47,
                            DayOfWeek = 4,
                            DeliveryId = 17,
                            EmployeeId = 1,
                            StoreId = 9,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 48,
                            DayOfWeek = 4,
                            DeliveryId = 18,
                            EmployeeId = 1,
                            StoreId = 10,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 49,
                            DayOfWeek = 4,
                            EmployeeId = 1,
                            StoreId = 6,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 50,
                            DayOfWeek = 4,
                            EmployeeId = 1,
                            StoreId = 7,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 51,
                            DayOfWeek = 4,
                            DeliveryId = 19,
                            EmployeeId = 2,
                            StoreId = 4,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 52,
                            DayOfWeek = 4,
                            DeliveryId = 20,
                            EmployeeId = 2,
                            StoreId = 5,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 53,
                            DayOfWeek = 4,
                            EmployeeId = 2,
                            StoreId = 1,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 54,
                            DayOfWeek = 4,
                            EmployeeId = 2,
                            StoreId = 2,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 55,
                            DayOfWeek = 4,
                            EmployeeId = 2,
                            StoreId = 3,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 56,
                            DayOfWeek = 4,
                            DeliveryId = 16,
                            EmployeeId = 3,
                            StoreId = 8,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 57,
                            DayOfWeek = 4,
                            DeliveryId = 17,
                            EmployeeId = 3,
                            StoreId = 9,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 58,
                            DayOfWeek = 4,
                            DeliveryId = 18,
                            EmployeeId = 3,
                            StoreId = 10,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 59,
                            DayOfWeek = 4,
                            DeliveryId = 19,
                            EmployeeId = 3,
                            StoreId = 4,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 60,
                            DayOfWeek = 4,
                            DeliveryId = 20,
                            EmployeeId = 3,
                            StoreId = 5,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 61,
                            DayOfWeek = 5,
                            DeliveryId = 21,
                            EmployeeId = 1,
                            StoreId = 1,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 62,
                            DayOfWeek = 5,
                            DeliveryId = 22,
                            EmployeeId = 1,
                            StoreId = 2,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 63,
                            DayOfWeek = 5,
                            DeliveryId = 23,
                            EmployeeId = 1,
                            StoreId = 3,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 64,
                            DayOfWeek = 5,
                            EmployeeId = 1,
                            StoreId = 4,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 65,
                            DayOfWeek = 5,
                            EmployeeId = 1,
                            StoreId = 5,
                            Type = "Write Order"
                        },
                        new
                        {
                            StopId = 66,
                            DayOfWeek = 5,
                            DeliveryId = 24,
                            EmployeeId = 2,
                            StoreId = 6,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 67,
                            DayOfWeek = 5,
                            DeliveryId = 25,
                            EmployeeId = 2,
                            StoreId = 7,
                            Type = "Delivery"
                        },
                        new
                        {
                            StopId = 68,
                            DayOfWeek = 5,
                            EmployeeId = 2,
                            StoreId = 8,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 69,
                            DayOfWeek = 5,
                            EmployeeId = 2,
                            StoreId = 9,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 70,
                            DayOfWeek = 5,
                            EmployeeId = 2,
                            StoreId = 10,
                            Type = "Merchandise"
                        },
                        new
                        {
                            StopId = 71,
                            DayOfWeek = 5,
                            DeliveryId = 21,
                            EmployeeId = 3,
                            StoreId = 1,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 72,
                            DayOfWeek = 5,
                            DeliveryId = 22,
                            EmployeeId = 3,
                            StoreId = 2,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 73,
                            DayOfWeek = 5,
                            DeliveryId = 23,
                            EmployeeId = 3,
                            StoreId = 3,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 74,
                            DayOfWeek = 5,
                            DeliveryId = 24,
                            EmployeeId = 3,
                            StoreId = 6,
                            Type = "Drop Off"
                        },
                        new
                        {
                            StopId = 75,
                            DayOfWeek = 5,
                            DeliveryId = 25,
                            EmployeeId = 3,
                            StoreId = 7,
                            Type = "Drop Off"
                        });
                });

            modelBuilder.Entity("Repository.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("PlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            Lat = 42.984206999999998,
                            Long = -87.912901000000005,
                            PlaceId = "ChIJfZyRV2oXBYgR_hLJNn-fnEg",
                            ScheduleId = 1,
                            StoreName = "Pick n Save Holt",
                            StreetAddress = "250 W Holt Ave, Milwaukee, WI, 53207"
                        },
                        new
                        {
                            StoreId = 2,
                            Lat = 42.968153999999998,
                            Long = -88.009032000000005,
                            PlaceId = "ChIJpUBh1isQBYgR1nJjjs36yVE",
                            ScheduleId = 2,
                            StoreName = "Pick n Save Coldspring",
                            StreetAddress = "4279 S 76th St, Greenfield, WI 53220"
                        },
                        new
                        {
                            StoreId = 3,
                            Lat = 42.997154000000002,
                            Long = -88.049858,
                            PlaceId = "ChIJ-wwouYMPBYgRugMGerzM4Ec",
                            ScheduleId = 3,
                            StoreName = "Pick n Save Cleveland",
                            StreetAddress = "2625 S 108th St, West Allis, WI 53227"
                        },
                        new
                        {
                            StoreId = 4,
                            Lat = 42.997076,
                            Long = -88.045524,
                            PlaceId = "ChIJuXhmDoQPBYgRK8eTQCbhzRw",
                            ScheduleId = 4,
                            StoreName = "Target West Allis",
                            StreetAddress = "2600 S 108th St, West Allis, WI 53227"
                        },
                        new
                        {
                            StoreId = 5,
                            Lat = 42.939061000000002,
                            Long = -88.045790999999994,
                            PlaceId = "ChIJ8fooCWQOBYgRXnOW9RqNh68",
                            ScheduleId = 5,
                            StoreName = "Pick n Save Hales Corners",
                            StreetAddress = "5800 S 108th St, Hales Corners, WI 53130"
                        },
                        new
                        {
                            StoreId = 6,
                            Lat = 42.939061000000002,
                            Long = -88.045790999999994,
                            PlaceId = "ChIJn_sIpcMIBYgRoDPHQpNiEh4",
                            ScheduleId = 6,
                            StoreName = "Pick n Save New Berlin",
                            StreetAddress = "15445 W National Ave, New Berlin, WI 53151"
                        },
                        new
                        {
                            StoreId = 7,
                            Lat = 42.908267000000002,
                            Long = -88.125995000000003,
                            PlaceId = "ChIJFV_PrMsLBYgRFkmNWGjYHu0",
                            ScheduleId = 7,
                            StoreName = "Pick n Save Muskego",
                            StreetAddress = "Janesville Rd S74 W17005, Muskego, WI 53150"
                        },
                        new
                        {
                            StoreId = 8,
                            Lat = 42.896918999999997,
                            Long = -87.915362999999999,
                            PlaceId = "ChIJST_O6UIUBYgRJctdFiQ0ofw",
                            ScheduleId = 8,
                            StoreName = "Woodmans Oak Creek",
                            StreetAddress = "8131 S Howell Ave, Oak Creek, WI 53154"
                        },
                        new
                        {
                            StoreId = 9,
                            Lat = 42.960138999999998,
                            Long = -88.044126000000006,
                            PlaceId = "ChIJk_y7zFQOBYgRew-_R_fb4nc",
                            ScheduleId = 9,
                            StoreName = "Walmart Layton Ave",
                            StreetAddress = "10600 W Layton Ave, Greenfield, WI 53228"
                        },
                        new
                        {
                            StoreId = 10,
                            Lat = 42.926501000000002,
                            Long = -88.110527000000005,
                            PlaceId = "ChIJi5-Z_t0LBYgR_IeEp3884As",
                            ScheduleId = 10,
                            StoreName = "Walmart Muskego",
                            StreetAddress = "W159s6530 Moorland Rd, Muskego, WI 53150"
                        });
                });

            modelBuilder.Entity("Repository.Models.Employee", b =>
                {
                    b.HasOne("Repository.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.Route", b =>
                {
                    b.HasOne("Repository.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.RouteStore", b =>
                {
                    b.HasOne("Repository.Models.Route", "Route")
                        .WithMany("RouteStores")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Models.Store", "Store")
                        .WithMany("RouteStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.ScheduleStop", b =>
                {
                    b.HasOne("Repository.Models.Schedule", "Schedule")
                        .WithMany("ScheduleStops")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Models.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.Stop", b =>
                {
                    b.HasOne("Repository.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId");

                    b.HasOne("Repository.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Models.Store", b =>
                {
                    b.HasOne("Repository.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
